title: Dylan's Projects
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dylant168.github.io/just-the-doc-website/

aux_links:
  DylanT168 Github page: https://github.com/DylanT168/
